### ISSUE TITLE
Zusammensetzen des Topics fehlerhaft?

### ISSUE THREAD

**Issue by MarkusKress** [Schnup89/OpenV_NodeMCU#1]
Kann es sein, dass das Topic nicht korrekt zusammengesetzt wird? Die Topics sollten doch eigentlich mit "VITOWIFI/" beginnen. Doch der strcpy ersetzt das "VITOWIFI/" komplett durch den Namen des Datenpunktes. Also statt "VITOWIFI/gettempa" wird nur noch ""gettempa" als Topic gesetzt.

Daher statt:
strcpy(outName,dp.getName());
Besser:
strcat(outName,dp.getName());

Mir ist das aufgefallen, als ich mit 
mosquitto_sub -t 'VITOWIFI/#' -v -R 
keine Meldungen außer 
VITOWIFI/$status/online 1
bekommen habe.

**Comment by OrionVIII** [comment]
Habe das in meinem [fork](https://github.com/OrionVIII/OpenV_NodeMCU) korrigiert. Den fork habe ich gemacht, weil meine Anlage nur einen Heizkreis hat und ich teilweise auch andere Adressen verwende als Schnup89.

**Comment by Schnup89** [comment]
Vielen Dank, hab es angepasst!
