### ISSUE TITLE
NodeMCU Vitocal 242-s Heat pump

### ISSUE THREAD

**Issue by Bojkas1985** [Schnup89/OpenV_NodeMCU#2]
Hi, I have such a problem.
Vitocal 242-s heat pump with Vitotronic 200 WO1C
NodeMCU V3
Construction https://github.com/openv/openv/wiki/Bauanleitung-ESP32-Adafruit-Feather-Huzzah32-and-Proto-Wing
MQTT Broker - https://www.cloudmqtt.com/
Addresses: https://github.com/openv/openv/wiki/Adressen-W%C3%A4rmepumpen-Vitotronic-WO1C

Unfortunately, he doesn't read anything at all. I do not know exactly which side I should put IR and which phototransistor, I tried both options, but I assume IR to green light. When turned on in Broker it only prints VITOWIFI / $ status / online = 1.
What can I do? I'm doing something wrong? Missing something?

Thank you

**Comment by OrionVIII** [comment]
I used IR-LED 3MM TYP L-934SF4C and PHOTO-TRANS. SFH309FA-3/4 T1 OSR, resistors are the same (180 ohms and 10kohms)
The Photo-Transistor must face the green light, the IR the other (dark hole).
With my first adapter I found that any daylight passing by the holes caused problems, so then I used the housing here, that has a cover: [https://github.com/saidlm/Viessmann-optical-interface](url) and prevents "wrong" light

**Comment by Schnup89** [comment]
Thanks @OrionVIII ,Closing this issue
