### ISSUE TITLE
Links relativ statt absolut

### ISSUE THREAD

**Issue by ghwc2015** [Schnup89/OpenV_NodeMCU#3]
Hallo,

wenn die Links in der WebGUI relativ, statt absolut angegeben werden, dann funktionieren diese auch wenn man das Gerät nicht mit dem Namen "vitowifi.lan" ansprechen kann.

https://github.com/Schnup89/OpenV_NodeMCU/blob/2177863820951b69c3061a62dfef8fe47ff794d8/VitoWifi_NodeMCU.ino#L249

Also statt `<a href='http://vitowifi.lan/start'>` besser `<a href='/start'>` etc.

**Comment by Schnup89** [comment]
Danke dir!
Hab es entsprechend angepasst.
