### ISSUE TITLE
Build 

### ISSUE THREAD

**Issue by Pukkahq** [Schnup89/OpenV_NodeMCU#4]
I am trying to adapt your code to work with open energy monitor. it will accept an MQTT bases on emon/

I have built an esp8266, uploaded your code without changing it. I can see 1 topic "$status\online" but i am not seeing anything else also it only sends 1 message and does not update after 60 seconds

![image](https://user-images.githubusercontent.com/15746724/80710642-fbcf4f00-8ae6-11ea-8166-a71fcd804ae4.png)

Paul

**Comment by Schnup89** [comment]
Hi Paul,
sorry for the late response.
If there is only the status mqtt message sent out by the esp that indicates that the connection to the vissmann device is not working.
Please check your adapter and wiring
