### ISSUE TITLE
How does ÔTA work ?

### ISSUE THREAD

**Issue by BornTKill** [Schnup89/OpenV_NodeMCU#5]
Dear,

First of all, thank you for this project !
Can you explain me how to use http://ip/update ?

Best regards.

**Comment by Schnup89** [comment]
Hi,
sorry for the late response, but I don't know what you exactly mean.
You can change the Code in .ino file and compile and build the .bin file.
You can upload that .bin file with the webinterface so you dont have to connect the esp to your pc.
