### ISSUE TITLE
Bekomme keine daten

### ISSUE THREAD

**Issue by Kasper027** [Schnup89/OpenV_NodeMCU#6]
Hallo,
ich habe das Problem, dass ich keine daten Angezeigt bekomme.
Ich habe eine VC 200-S aus 2018. Regelung Typ WO1C.
Ich habe mir mal den Optolink mit einem Handy angeschaut, da blinkt ca. 1x die Sekunde die LED. Dass scheint also zu funktionieren. 
Habe folgenden [Schaltplan ](https://github.com/openv/openv/wiki/Bauanleitung-ESP32-Adafruit-Feather-Huzzah32-and-Proto-Wing)und dies am NodeMCU ESP8266 an 3,3V Gnd Rx und TX angeschlossen. Doch leider bekomme ich keine Daten. Ich habe schonmal die Daten mit einem USB-Adapter am Raspberry ausgelesen. Da musste ich aber noch die Device ID anpassen. Muss das hier auch gemacht werden? Wenn ja wie?
Hat sonst noch einer einen Rat, was ich tun könnte?

Grüße Kasper027

Edit:
Ich habe auch schon beide Protokolle versucht. P300 und KW. Aber jeweils kein Erfolg @Schnup89 Hast du noch eine Idee

**Comment by Schnup89** [comment]
Hey, teste mal die HEX-Werte anzupassen.

Zeile 39 zum Beispiel:
DPTemp getTempA("gettempa", "allgemein", 0x0800);
zu
DPTemp getTempA("gettempa", "allgemein", 0x01C1);

Den Wert 0x01C1 habe ich von hier:
https://github.com/openv/openv/wiki/Adressen-W%C3%A4rmepumpen-Vitotronic-WO1C

**Comment by Kasper027** [comment]
Achso, dass habe ich auch schon gemacht :-)

Ich versuche gerade mit sowohl einem ESP32 und einem ESP8266 überhaupt erstmal eine Verbindung auf zu bauen. Aktuell nur mit den VitoWifi-Beispielen. Aber da wird mir nie was angezeigt. 

Ich habe heute erfahren, dass ich kein SFH309FA sondern SFH310FA verbaut habe. Kann es damit zusammen hängen?

Hier einmal das Beispiel für den ESP32.
`
#include <VitoWiFi.h>
VitoWiFi_setProtocol(KW);
DPTemp outsideTemp("outsideTemp", "boiler", 0x01C1);
DPTemp boilerTemp("boilertemp", "boiler", 0x0102);
DPStat pumpStat("pump", "heating1", 0x2906);

void tempCallbackHandler(const IDatapoint& dp, DPValue value) {
  float fahrenheit = 0;
  fahrenheit = (5.0 / 9) * (value.getFloat() + 32);
  Serial.print(dp.getGroup());
  Serial.print(" - ");
  Serial.print(dp.getName());
  Serial.print(": ");
  Serial.println(fahrenheit, 1);  // print with 1 decimal
}

void globalCallbackHandler(const IDatapoint& dp, DPValue value) {
  Serial.print(dp.getGroup());
  Serial.print(" - ");
  Serial.print(dp.getName());
  Serial.print(" is ");
  char value_str[15] = {0};
  value.getString(value_str, sizeof(value_str));
  Serial.println(value_str);
}

void setup() {
  Serial.begin(115200);
  Serial.println(F("Setup finished..."));
  outsideTemp.setCallback(tempCallbackHandler);
  boilerTemp.setCallback(tempCallbackHandler);
  VitoWiFi.setGlobalCallback(globalCallbackHandler);  // this callback will be used for all DPs without specific callback
                                                      // must be set after adding at least 1 datapoint
  VitoWiFi.setup(&Serial1, 25, 26);  // 

}

void loop() {
  static unsigned long lastMillis = 0;
  if (millis() - lastMillis >= 1 * 60000L) {  // read all values every 60 seconds
    lastMillis = millis();
    Serial.println(lastMillis);
    VitoWiFi.readAll();
  }   
  VitoWiFi.loop();
}
`

Als Ausgabe bekomme ich folgendes:
`19:31:55.518 -> ⸮⸮ ⸮ ⸮⸮⸮ ⸮   B ⸮ =G⸮x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00  19:31:55.518 -> mode:DIO, clock div:1  19:31:55.518 -> load:0x3fff0018,len:4  19:31:55.518 -> load:0x3fff001c,len:1216  19:31:55.518 -> ho 0 tail 12 room 4  19:31:55.518 -> load:0x40078000,len:10944  19:31:55.518 -> load:0x40080400,len:6388  19:31:55.518 -> entry 0x400806b4  19:31:55.620 -> Setup finished...  19:32:55.617 -> 60000  19:33:55.595 -> 120000`


Kannst du damit etwas anfangen?

**Comment by Schnup89** [comment]
Der Output sieht mir nach dem Standard ESP32-Debug output aus, ich denke der bekommt keine Daten.
Die Pins (25,26) sind korrekt?
Hast du das Beispiel von hier? https://github.com/bertmelis/VitoWiFi/blob/master/examples/basic-esp32/basic-esp32.ino

Versuche mal dort eine issue zu öffnen, evtl. können dir die Leute dort besser helfen als ich.

**Comment by Kasper027** [comment]
So bin einen ganzen schritt weiter. Ich habe mir nochmal die Originale runter geladen. Mit dem ESP32 an den Pins 21 und 22 läuft alles. da kommen jede Minute nun Werte. Auch blinkt die LED.
Das ganze mit dem ESP8266 NodeMCU läuft nicht. Ebenso dein Script nicht. Da leuchtet dauerhaft die LED. Wenn ich RX und TX tausche, passiert gar nichts. 
Will nur nochmal richtig gehen. Bei deinem Script, wo schließe ich RX und TX an? An die GPIO1 und GPIO3 oder? Direkt neben den 3,3V und GND.

**Comment by Schnup89** [comment]
Hey, bitte beachte folgende Info aus der Anleitung:

`Mein NodeMCU wurde per USB-Kabel mit Strom versorgt und stellt die benötigten 3,3V und GND am entsprechenden Pin zur Verfügung. Der NodeMCU stellt zwei serielle Verbindungen zur Verfügung TXD0,RXD0(Serial0) und TXD2,RXD2(Serial1). Da die Verbindung mit den Serial1-Pin’s zum Optolink-Adapter nie wirklich funktioniert hatte, musste ich die Serial0 Ports nutzen. Hier bin ich auf große Probleme gestoßen, da die Serial0-Verbindung für die USB-Programmierung mitgenutzt wird. Wird also per Arduino-IDE der Sketch hochgeladen, wird unter Umständen der Upload des Sketch durch den Fotostransistor unterbrochen, oder verfälscht, sodass der NodeMCU im Anschluss nicht mehr den Sketch booten kann. Somit ist es wichtig, bei jedem Sktech-Upload die Verbindung zum Fototransistor zu trennen. Ein Workaround per Sketch-Upload über WLAN ist in meinem weiter unten genannten Sketch implementiert, sodass der Fototransistor nicht mehr getrennt werden muss um einen angepassten Sketch hochzuladen.`

Ich meine der ESP32 kann auf jeden gpio eine serielle Schnittstellenverbindung aufbauen.
Bei dem NodeMCU ist man hier an die Serial0 oder Serial1 PIN's gebunden.

Siehe die Pins RXD0, TXD0 (Serial0) oder RXD2,TXD2 (Serial1). 
https://i2.wp.com/randomnerdtutorials.com/wp-content/uploads/2019/05/ESP8266-NodeMCU-kit-12-E-pinout-gpio-pin.png?quality=100&strip=all&ssl=1

Genutzt wird gpio3 und gpio1 (Gekennzeichnet mit RX und TX).
Alternativ kannst du auch gpio13 und gpio15 nutzen dazu folgenden Code ändern:

`VitoWiFi.setup(&Serial);   -> VitoWiFi.setup(&Serial1);`

**Comment by Schnup89** [comment]
Vorsicht! Serial1 funktioniert nicht, da der RX-Pin vorbelegt ist, siehe hier:
http://arduino.esp8266.com/Arduino/versions/2.3.0/doc/reference.html#serial

Evtl. kannst du gpio13 und gpio15 mit Serial.swap() nutzen, welches du vor VitoWiFi.setup(&Serial); aufrufen musst

**Comment by Kasper027** [comment]
Deine Anleitung habe ich befolgt. Optolink beim ersten Flashen komplett vom RX und TX getrennt.

> Siehe die Pins RXD0, TXD0 (Serial0) oder RXD2,TXD2 (Serial1).

So wie ich es jetzt verstanden habe, ist das nicht ganz richtig.
RXD0->GPIO3 und TXD0->GPIO1 sind Serial
TXD1->GPIO 2 ist Serial1
RXD2->GPIO13 und TXD2->GPIO15 sind Serial.swap

Ich habe nun als erstes mit Serial1 versucht. Damit geht es nicht.
Danach habe ich nochmal den Optolink abgesteckt, neue Firmware nur mit Serial hochgeladen, Optolink wieder auf gesteckt, Nun blinkt wieder die LED im Sekunden Rythmus. Aber ich bekomme noch immer keine Daten.

Gibt es bei dir eine Möglichkeit, in deinem Sketch rohdaten anzeigen zu lassen? 
Oder hat einer schonmal die Beispielscripte mit dem ESP8266 ans laufen gebracht? Ich verstehe dabei noch nicht so ganz, wie ich mit einem ESP8266 wo ja Serial auch gleichzeitig die USB-Schnittstelle ist, Daten zu testen. So wie bei dem ESP32 wo ich zwei getrennte Serielle Schnittstellen habe, hat es ja funktioniert.

**Comment by Kasper027** [comment]
Ach ja, der Online-Status wird per MQTT sauber mit einer 1 übertragen. Also die MQTT-Schnittstelle läuft schonmal

**Comment by Schnup89** [comment]
Kommst du auf die Weboberfläche? Wenn ja, schau mal nach der Uptime, nicht dass der NodeMCU die ganze Zeit bootet.
Leider funktioniert das debugging nicht da wir die serielle Schnittstelle für die Verbindung zum Adapter nutzen.

**Comment by Kasper027** [comment]
![image](https://user-images.githubusercontent.com/35900030/152601963-da65ca81-80a1-4ac3-bfe9-d0ec0b3bb3c6.png)
die läuft hoch.

**Comment by Schnup89** [comment]
Probiere alternativ mal das Blync Beispiel aus:
https://github.com/bertmelis/VitoWiFi/blob/master/examples/Blynk/Blynk.ino

Da sollten dann Daten rauspurzeln.

**Comment by Kasper027** [comment]
Hey @Schnup89 Ich habe gerade das Blync ausprobiert. Verstehe dabei aber nicht die Verbindung. Meiner Meinung fehlt da noch was im Code (Template_ID und Device_Name).
Mit dem Standart-Code komme ich nicht weiter.

Ich habe nun mal eine Frage im VitoWiFi geschrieben. Mal sehen, was dabei raus kommt.

P.S. Danke schonmal für deine Hilfe

**Comment by Kasper027** [comment]
Da ich aktuell leider nicht so recht weiter komme mit dem ESP8266 versuche ich gerade den Ganzen Code auf einem ESP32 zum laufen zu bringen. Kann mir da einer weiter helfen?
Für den Start habe ich erstmal alles, was mit dem Server zu tun hat auskommentiert. Jetzt habe ich nur das Problem, dass ich das ganze mit dem WiFiEventHandler auf ESP32 Basis nicht verstehe.
![image](https://user-images.githubusercontent.com/35900030/152646778-7d77249b-e7aa-4c69-af92-bf794dc0f51e.png)

Kannst du mir sagen, wie ich das umschreiben müsste, damit das ganze auch auf einem ESP32 läuft?

**Comment by Kasper027** [comment]
Leider komme ich nicht wirklich weiter mit dem ESP8266. Deswegen bin ich nun dabei, alles auf dem ESP32 zum laufen zu bringen. Doch leider komme ich nicht weiter. Vllt kannst du mir da weiter helfen.
Zum Vorgehen, Ich habe erstmal alles was mit dem Webserver zu tun hatte, auskommentiert.
Naja, dann erstmal alles, was nicht ging, versucht, zu reparieren :-) Dass sollte nun fast geglückt sein.
Nun hänge ich aber an einer Stelle, (und dass scheint die gleiche wie mit dem ESP8266 zu sein).
1. Der ESP selber verbindet sich mit dem Wlan
2. MQTT Verbindung steht auch. Der Online Status wird mit "1" geschrieben
3. Danach läuft die Zeit sauber ab. 

Um das ganze ein bisschen besser nachvollziehen zu können, habe ich noch ein paar Serial.Print Kommentare mit eingefügt:

Hier einmal die meine Ino Datei
[sketch_esp32.zip](https://github.com/Schnup89/OpenV_NodeMCU/files/8008926/sketch_esp32.zip)

Und hier die Ausgabe:
![image](https://user-images.githubusercontent.com/35900030/152659126-407d94df-81e3-47d4-8658-8da7e68dee73.png)

Nun die Große Frage, warum holt er keine Daten ab und schreibt mir diese wie in Zeile 198 gefordert aus?
`void tempCallbackHandler(const IDatapoint& dp, DPValue value) {
  //Umwandeln, und zum schluss per mqtt publish an mqtt-broker senden
  char outVal[9];
  dtostrf(value.getFloat(), 6, 2, outVal);
  char outName[30] = "VITOWIFI/";
  strcat(outName,dp.getName());
  mqttClient.publish(outName, 1, true, outVal);
  Serial.print(outVal); `

Kannst du mir helfen?

**Comment by Schnup89** [comment]
Hey, bStopVito wird bei dir mit true anstatt false initialisiert.
Dadurch wird der Block hier nie ausgeführt:
```
 VitoWiFi.loop();
    if (updateVitoWiFi && mqttClient.connected()) {
      updateVitoWiFi = false;
      VitoWiFi.readAll();
    }
```

Setze in deiner .ino Zeile 17 die Variable auf false und teste nochmal.

**Comment by Kasper027** [comment]
Hey @Schnup89 
Vielen Dank. Das hat nun geklappt. Ich hatte es probiert schonmal probiert. Aber scheinbar liegt der Fehler tiefer begraben. Sobald i-was am VitoWiFi nicht stimmt, läuft zwar die Firmware, wird aber andauernd unterbrochen. Somit konnte ich da ohne Ende testen, aber es lag dann wahrscheinlich an den Daten, die abgerufen werden sollen.
Ich bin nun soweit, dass Temperatur-Ist und Soll eingeladen bekomme. Jetzt muss ich nur noch richtig verstehen, wie ich gelesene Daten richtig abändern kann. Denn sobald ich zum Beispiel den Betriebsmodus einprogrammiert habe, sendet der ESP32 noch die Temperaturwerte, danach stürzt er aber komplett ab und startet neu.

**Comment by Kasper027** [comment]
Des weiteren sind es bei beinen Temperaturen andere Adressen wie [hier ](https://github.com/openv/openv/wiki/Adressen-W%C3%A4rmepumpen-Vitotronic-WO1C) angegeben. Diese Adressen haben 3 anstatt 2 Bytes. So wie ich es verstanden habe nun, erst ein sINT16 mit dem Wert und dann noch mit nem uINT8 einen Status. Jetzt muss ich probieren, wie ich das sauber eingelesen bekommen kann.

**Comment by Schnup89** [comment]
Ich würde folgendermaßen vorgehen:
- Nur Temperatur abrufen und prüfen ob der ESP über mehrere Zyklen ohne reboot durchläuft

- weitere Werte Stück für Stück reinnehmen und schauen ob es klappt.

**Comment by Kasper027** [comment]
Hey @Schnup89 
Ich wollte mich nun nochmal bedanken bei dir. Bei mir läuft nun alles. Halt auf dem ESP32 anstatt auf dem 8266. Warum halt auch immer.

Ich habe noch eine Frage bzgl. der MQTT daten. Aktuell wird wohl nur eine Änderung des Wertes weiter gegeben. Kannst du mir sagen, wie ich immer die Werte schicke und aktualisieren kann? So sehen die Graphen sehr komisch aus

![MQTT Daten](https://user-images.githubusercontent.com/35900030/160905058-2373921e-2e67-43d2-8ffb-f299ddfde703.PNG)

Die dicken Linien sind der eig Verlauf

**Comment by Schnup89** [comment]
Servus, gerne doch, manchmal will man gar nicht wissen warum ;)

Dein Problem kannst du leider nicht auf dem ESP lösen, denn dieser sendet die Daten im festgelegten Intervall immer an den MQTT-Broker auch wenn die Werte sich nicht verändert haben.

Ich denke dein MQTT Client/Server ignoriert die MQTT-Message mit gleichen Werten und dein Graph stellt die Kurve nicht so dar wie du es gerne hättest.
Aus meiner Sicht hast du zwei Leistungsansätze die du untersuchen kannst:
- Deinen MQTT Client der VIS prüfen ob es eine Einstellung gibt die das speichern gleicher Werte verhindert
- Evtl. gibt es eine Einstellung in deiner VIS/Graph der die "falsche" Linie verhindert.

**Comment by Kasper027** [comment]
Hey Danke für den Tipp. Habe es gefunden
