### ISSUE TITLE
Liefert nix

### ISSUE THREAD

**Issue by dirk-schulz** [Schnup89/OpenV_NodeMCU#7]
Hallo, Ich würde mich freuen, wenn Du mir weiterhelfen könntest. Ich versuche das gerade nachzubauen (Viessmann 200, NodeMCUv2 oder V3, Home assistant).
Der Sketch läuft auf der NodeMCU und liefert per MQTT online=1. Aber leider bekomme ich keinerlei Daten von der Heizung.
Erste Vermutung: Schaltung: Kannst Du mir hier nochmal den Aufbau skizzieren? Ich hatte mich hiernach gerichtet: https://github.com/openv/openv/wiki/Bauanleitung-ESP32-Adafruit-Feather-Huzzah32-and-Proto-Wing  Ist am NodeMCU an TX und RX (also UART0), richtig? Bei dem Lesekopf: Anode und Collector sind jeweils die kurzen Beinchen? Fototransitor (schwarz) kommt an rechts an die grüne Status-LED der Heizung? Und die Infrarot LED kommt links?

**Comment by jenswalit** [comment]
Ja gleiches Problem auch bei mir. Hast du es hinbekommen?

**Comment by dirk-schulz** [comment]
Ja, zumindest bin ich einen Schritt weiter und bekomme erste Werte von der Heizung. 
Change 1: statt nodemcu mit esp8266 verwende ich jetzt ein esp32. Da klappte die compilierung mit Ports für Serial2 (TX2 und RX2). Allerdings immer noch keine Werte. 
Change2: man drehe entgegen der obige Anleitung die  Vishay TSHA4401 LED. Ein Durchgangsprüfer zeigte mir, dass entgegen Datenblatt und Anleitung (link oben aber auch Esp8266 Bauanleitung auf openv) der Durchgang andersherum ist. Also Anode ist bei mir nun mit TX2 verbunden und die Kathode (langes Beinchen) mit dem Widerstand. 
Und siehe da, erster Wert auf 0°C.
Change3: Noch suche ich mir derzeit die Adressen zusammen. Habe eine Vitodens 200 WB2C und irgendwie passen die bei openv dargestellten Adressen nicht immer. So suche ich zum Beispiel noch die Raum Soll Temp, die derzeit mit sportlichen 5034,27°C ausgelesen wird. Partymodus, Brennerstatus zeigen nicht korrekt an.  Hat da jemand eine Adressübersicht für eine Wb2c??? 
Aber Kessel Temp, Modus und Warmwasser Speicher Temp tun es schon.

Nachdem es nun mit esp32 geht und die Hardware läuft, wollte ich es demnächst auch noch mal mit den nodemcu testen. Weiß nur noch nicht, wie ich das mit dem Port am esp8266 löse.
Mache das direkt in esphome in Home Assistant.

Also Tipp wäre die Polung der LED zu prüfen. ;-)

**Comment by jenswalit** [comment]
Super ich werde es Mal testen. Vielen Dank Am 16.10.2022 21:47 schrieb dirk-schulz ***@***.***>:

Ja, zumindest bin ich einen Schritt weiter und bekomme erste Werte von der Heizung.

Change 1: statt nodemcu mit esp8266 verwende ich jetzt ein esp32. Da klappte die compilierung mit Ports für Serial2 (TX2 und RX2). Allerdings immer noch keine Werte.

Change2: man drehe entgegen der obige Anleitung die  Vishay TSHA4401 LED. Ein Durchgangsprüfer zeigte mir, dass entgegen Datenblatt und Anleitung (link oben aber auch Esp8266 Bauanleitung auf openv) der Durchgang andersherum ist. Also Anode ist bei mir nun mit TX2 verbunden und die Kathode (langes Beinchen) mit dem Widerstand.

Und siehe da, erster Wert auf 0°C.

Change3: Noch suche ich mir derzeit die Adressen zusammen. Habe eine Vitodens 200 WB2C und irgendwie passen die bei openv dargestellten Adressen nicht immer. So suche ich zum Beispiel noch die Raum Soll Temp, die derzeit mit sportlichen 5034,27°C ausgelesen wird. Partymodus, Brennerstatus zeigen nicht korrekt an.  Hat da jemand eine Adressübersicht für eine Wb2c???

Aber Kessel Temp, Modus und Warmwasser Speicher Temp tun es schon.

Nachdem es nun mit esp32 geht und die Hardware läuft, wollte ich es demnächst auch noch mal mit den nodemcu testen. Weiß nur noch nicht, wie ich das mit dem Port am esp8266 löse.

Mache das direkt in esphome in Home Assistant.

Also Tipp wäre die Polung der LED zu prüfen. ;-)

**Comment by jenswalit** [comment]
Kannst Du mir vielleicht deinen Sketch geben ich krieg das nicht ans laufen. Nutzt du VCode oder Arduino.

**Comment by dirk-schulz** [comment]
Hallo, ich mache dies direkt mit esphome im Home Assistant. Dort wird es dann compiliert und auf den esp32 hochgeladen. Kann Dir dazu nur die Yaml und die angepasste optolink.h schicken, falls Du auch HA nutzt. 
Als einzigen Sketch kann ich nur das für den nodemcu (esp8266) anbieten, aber da konnte ich es selbst noch nicht testen, ob es mit lesen klappt. (das hatte ich damals per Andruino SDK gemacht)
Was hilft Dir besser weiter?

**Comment by jenswalit** [comment]
Je perfekt wenn das direkt mit esphome geht dann baue ich mir etwas.

**Comment by jenswalit** [comment]
Ich habs gefunden, was hast du mit dem Eintrag <<: !include common/common.yaml gemacht?

Kannst Du mir mal deine yaml und die daten schicken?

Kommen da die Befehle rein?

Vielen Dank

Gruß Jens

**Comment by dirk-schulz** [comment]
Hallo Jens,
Also zum Setup in Home Assistant:
- lege unter /config/esphome/custom_components den Ordner optolink an. Darein kommt die datapoints.h sowie optolink.h
- Wenn Du bereits beim "!include" bist, hast Du also bereits eines Device unter esphome angelegt, richtig? (Ansonsten Gerät anlegen. Bei mir heißt das esp32-viessmann
- Am besten einmal bereits auf dem esp32 installieren lassen (per USB anschließen und dann mittels Install "plug into this computer" installieren lassen)
- Dann die Config des Geräts ändern. Darein nun die Zeilen vom esp32-viessmann kopieren.
- installieren lassen
Nutzt Du denn ein ESP32? Wenn Du ein nodemcu hast, wird das auf einen Fehler laufen. 
Im Falle von nodemcu musst Du in der Device config (yaml) den Abschnitt "esp32:" löschen und stattdessen 
platform: ESP8266
board: nodemcuv2
im Abschnitt "esphome:" ergänzen. UND beim nodemcu muss die optolink.h angepasst werden: Hier muss die Zeile 
"VitoWiFi.setup(&Serial, RX2, TX2);" 
geändert werden in  "VitoWiFi.setup(&Serial);"

Bei den nächsten Änderungen (z.B. andere Adressen) kannst Du das auch per "Wireless" installieren lassen.

Viel Spaß und Erfolg beim Ausprobieren!
Lass mich gerne wissen, falls Du ein nodemcu (esp8266) benutzt und ob das bei Dir funktioniert.

[datapoints.h.txt](https://github.com/Sch
[esp32-viessmann.txt
[optolink.h.txt](https://github.com/Schnup89/OpenV_NodeMCU/files/9814408/optolink.h.txt)
](https://github.com/Schnup89/OpenV_NodeMCU/files/9814405/esp32-viessmann.txt)
nup89/OpenV_NodeMCU/files/9814404/datapoints.h.txt)

**Comment by jenswalit** [comment]
Hallo Dirk,

ich habe alle erfolgreich auf dem ESP32 drauf, nur bekomme ich keine Werte. Ich habe schon alles hin und her gedreht.

Welche LED ist rechts und welche links also da wo die grüne leuchtet die 309 oder die 487 ?

Ich hab echt keine Ahnung warum nix kommt. Kannst du sagen in welchen Abständen die Abfragen gemacht werden? Oder kann ich das irgendwie debuggen ob da irgend eine Kommunikation statt findet?

**Comment by dirk-schulz** [comment]
309 (schwarz) gehört über die grüne LED.
Was hält diese vor die grüne LED?
Ich habe mir von openv ein 3D Teil gedruckt. Laut Forum decken manche auch das ab, weil Umgebungslicht oder falscher Sitz über der LED zu Komm Störung führen kann.
Abfrage interval keine Ahnung, ab sobald man die Webseite des ESP per Browser erreicht, stehen 1-2 Sekunden danach Werte bei mir drin.
Womit ist die Anode des 487 verbunden? Ich selbst nutze stattdessen den Vishay TSHA4401

**Comment by dirk-schulz** [comment]
Liefert nun wie gewünscht die Werte
