### ISSUE TITLE
Beispiel für DPRaw

### ISSUE THREAD

**Issue by Sirmike2** [Schnup89/OpenV_NodeMCU#9]
Hallo, 

ich habe dein Programm bei meiner Viessmann Heizung dementsprechend umgesetzt. Funktioniert echt top.
Ich bin mir aber nicht sicher welche Version der Heizung und Steuerung ich wirklich habe, dazu wollte ich die Adresse 0x00F8 auslesen. Leider bin ich nicht so gut im Programmieren. Ich wollte DPRaw benutzen um den Hexwert zu bekommen. Ich bekomme es aber nicht umgesetzt. Es müsste ja, zumindest laut VitoWIfi irgendwie mit .setLength() und getRaw() funktionieren.
Kannst du so ein Beispiel mal mit einbauen oder hier kurz mal reinstellen? Wäre echt super.

Danke!

**Comment by Schnup89** [comment]
Hi, sorry habe deinen Issue irgendwie nicht gesehen.
Ist das noch aktuell?

**Comment by Sirmike2** [comment]
Danke für die Rückmeldung, hab's bereits hinbekommen.
